# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoFilesTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'AlamofireImage'
  # Pods for VideoFilesTask

  target 'VideoFilesTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoFilesTaskUITests' do
    # Pods for testing
  end

end

